### ISSUE TITLE
Voice missing, rapid dialogue box cycling at Baba Yaga's skull

### ISSUE THREAD

**Issue by mikequeisser** [AshLancer/QFG4-Enhanced#7]
I noticed that when talking to the skull outside Baba Yaga's hut, the dialogue boxes cycle quickly at these points-
* When discussing needing the hat
* The elderberry pie recipe
There is no voiceover either.

**Comment by Architekt909** [comment]
This is apparently an issue in general with the game due to it missing voice lines. In order to work around it, whether with this patch or not, you need to switch the game to text only instead of dialog or dialog + text to give you time to read it.

**Comment by mikequeisser** [comment]
Good to know. Thanks, I'll close this out.
